---
# tasks file for ansible-role-courier/

- name: Install base packages
  apt:
    name:
      - courier-base
      - courier-imap
      - courier-maildrop
  notify: Restart courier-imap

- name: Install base packages
  apt:
    name: courier-imap-ssl
  when: courier_ssl
  register: installed_imap_ssl
  notify: Restart courier-imap-ssl

- name: Remove default dhparams.pem
  file:
    path: /etc/courier/dhparams.pem
    state: absent
  # noqa 503
  when: installed_imap_ssl.changed

- name: Copy renew_dhparams.sh
  copy:
    src: renew_dhparams.sh
    dest: /etc/courier/renew_dhparams.sh
    mode: 0755

- name: Regenerate dhparams.pem
  command: /etc/courier/renew_dhparams.sh
  args:
    creates: /etc/courier/dhparams.pem

- name: Generate imapd.pem ssl certificate
  shell: cat {{ courier_ssl_certificate_key }} {{ courier_ssl_certificate }} > /etc/courier/imapd.pem
  args:
    executable: /bin/bash
  when: courier_ssl
  notify: Restart courier-imap-ssl

- name: Add cronjob for courier-imap-ssl
  cron:
    name: dhparams renewal
    job: /etc/courier/renew_dhparams.sh
    user: root
    day: 1
    hour: 1
    minute: 1
  when: courier_ssl

- name: Copy default maildroprc
  loop:
    - /etc/maildroprc
    - /etc/courier/maildroprc
  copy:
    src: maildroprc
    dest: "{{ item }}"

- name: Install sasl requirements (Debian)
  apt:
    name:
      - libsasl2-2
      - sasl2-bin
      - libsasl2-modules
